### PR TITLE
Add setting to configure Inertia views path

### PR DESCRIPTION
**Pull request by Yiddishe-Kop**
This PR allows the user to configure the path to the Inertia views in his project.

The Inertia views path is currently hardcoded to `/resources/js/Pages`, but some people tend to organize their project differently, for example I put them in `/resources/views/Pages`.

This PR adds a `inertia.viewsPath` setting. It still defaults to the current value.

Thanks for this amazing extension!

### CODE REVIEW

**Comment by gainlinejono** [comment]
I was wondering why it wasn't picking up my Inertia vue files, this is why!

**Comment by they-cloned-me** [comment]
+1 one this.
I use TypeScript and currently have my views at `resources/ts/pages/**`

**Comment by lcdss** [comment]
I also use `pages` instead of `Pages` and it would great to be able to define the correct path. The only downside of this is that if you use different paths on different projects you need to define the path once per project/workspace. Surely finding the correct path through the file calling `createInertiaApp` would be ideal, but this way solve the problem until an automatically detection is implemented.

**Comment by they-cloned-me** [comment]
> Instead of a config value in the plugin, this value is already set in multiple places in the app-code, can't we get the value from there?
> 
> For example in the Inertia config: https://github.com/inertiajs/inertia-laravel/blob/2.x/config/inertia.php#L48-L52
> 
> It could also be parsed from the `resolve` method (https://github.com/inertiajs/inertia/blob/master/packages/vue3/src/createInertiaApp.ts#L24), but that seems a lot more complicated, as that method can also contain logic

Your solution seems reasonable, but I don't think you should change your app's structure or internal configs to fit the extension—it should be the other way around.
It would be ideal to have an option to configure the extension (maybe in VSCode’s `settings.json`) since it's more disposable compared to your app's structure.
Just my 2 cents 🤷🏿‍♂️

**Comment by RobertBoes** [comment]
> Your solution seems reasonable, but I don't think you should change your app's structure or internal configs to fit the extension—it should be the other way around. It would be ideal to have an option to configure the extension (maybe in VSCode’s `settings.json`) since it's more disposable compared to your app's structure. Just my 2 cents 🤷🏿‍♂️

Not sure I understand the issue you're mentioning. The Inertia config is already present, you would already update that config if you change the pages path (or use multiple), as that's used for testing to verify page components exist (https://inertiajs.com/testing#endpoint-tests). You're not changing the app to account for a VSCode extension, it would be leveraging something that's already present and provides the info needed to determine where page components are located.

**Comment by they-cloned-me** [comment]
> > Your solution seems reasonable, but I don't think you should change your app's structure or internal configs to fit the extension—it should be the other way around. It would be ideal to have an option to configure the extension (maybe in VSCode’s `settings.json`) since it's more disposable compared to your app's structure. Just my 2 cents 🤷🏿‍♂️
> 
> Not sure I understand the issue you're mentioning. The Inertia config is already present, you would already update that config if you change the pages path (or use multiple), as that's used for testing to verify page components exist (https://inertiajs.com/testing#endpoint-tests). You're not changing the app to account for a VSCode extension, it would be leveraging something that's already present and provides the info needed to determine where page components are located.
> 
> Having a VSCode setting would mean you'd need to update the VSCode config for every single project. I have multiple projects that use different structures, so while the apps are already setup properly, I'd need to update that config value in every single workspace. Team members would need to do the same. While the location of the page components is already present in the Inertia config.

That makes sense, especially with the extra info. 
I agree, your solution seems like the best option. 🤝🏿

**Comment by joetannenbaum** [comment]
I dug @RobertBoes idea and implemented this in the just released 0.1.13. The extension should now pick up your paths/valid extensions based on the config, automatically.

**Comment by they-cloned-me** [comment]
Thank you

**Pull request closed without merging**
